# Generated by Django 3.1.3 on 2020-11-22 20:37

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=128, validators=[accounts.validators.validate_password]),
        ),
    ]
