# Generated by Django 3.1.3 on 2020-11-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201123_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
