# Generated by Django 3.1.3 on 2020-11-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomsreservations',
            name='meeting_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.meetingrooms'),
        ),
    ]
