# Generated by Django 3.1.3 on 2020-11-19 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_meetingroomsreservations_meeting_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'MeetingRoom',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(0, 'Valid'), (1, 'Cancelled')], default=0)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservationInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (1, 'Attending'), (0, 'Not attending')], default=-1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_reservations', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reservation')),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingroomsreservations',
            name='meeting_room',
        ),
        migrations.RemoveField(
            model_name='meetingroomsreservations',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='MeetingRooms',
        ),
        migrations.DeleteModel(
            name='MeetingRoomsReservations',
        ),
        migrations.AddField(
            model_name='reservation',
            name='invitees',
            field=models.ManyToManyField(through='main.ReservationInvite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.meetingroom'),
        ),
    ]
