# Generated by Django 3.1.3 on 2020-11-22 20:37

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201119_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateTimeField(validators=[main.validators.validate_date_from]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateTimeField(validators=[main.validators.validate_date_to]),
        ),
    ]
